######################################################################
# Automatically generated by qmake (3.1) Fri Jul 12 08:14:35 2019
######################################################################

TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS = transport test main

test.depends = transport
main.depends = transport

TRANSLATIONS += main/lang/en_us.ts  main/lang/zh_CN.ts
