######################################################################
# Automatically generated by qmake (3.1) Fri Jul 12 08:14:35 2019
######################################################################

TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS = main test
